# Generated by Django 5.1.6 on 2025-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=200, null=True)),
                ('Customer_since', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
