# Generated by Django 5.1.6 on 2025-03-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_p_code_product_product_code_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateField(default=0)),
                ('order_quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product')),
            ],
        ),
    ]
