# Generated by Django 5.1.6 on 2025-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, null=True)),
                ('p_code', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
