# Generated by Django 5.1.6 on 2025-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
